version: '3.8'
services:
  backend:
    build: .
    ports:
      - '8000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'blog_nest'
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - '33066:3306'